# Generated by Django 4.1 on 2022-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_employer_remove_category_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
